import { Button } from "../components/ui/button"; 
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-screen overflow-hidden">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen overflow-hidden flex flex-col`}
      >
        <nav className="flex gap-3 p-4 bg-white shadow-md rounded-md">
          <Button variant="ghost" asChild>
            <Link href="/">Home</Link>
          </Button>
          <Button variant="ghost" asChild>
            <Link href="/contato">Contato</Link>
          </Button>
          <Button variant="ghost" asChild>
            <Link href="/produtos">Produtos</Link>
          </Button>
          <Button variant="ghost" asChild>
            <Link href="/eventos">Eventos</Link>
          </Button>
          <Button variant="ghost" asChild>
            <Link href="/clientes">Clientes</Link>
          </Button>
          <Button variant="ghost" asChild>
            <Link href="/sobre-nos">Sobre Nós</Link>
          </Button>
        </nav>
        <main className="flex-grow">
          {children}
        </main>
      </body>
    </html>
  );
}
