import { Button } from "../components/ui/button";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link"; // importa o Link do Next.js
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <nav className="flex gap-4 p-4 bg-gray-200 rounded-lg mb-4">
  <Button asChild>
    <Link href="/">Home</Link>
  </Button>
  <Button asChild>
    <Link href="/contato">Contato</Link>
  </Button>
  <Button asChild>
    <Link href="/produtos">Produtos</Link>
  </Button>
  <Button asChild>
    <Link href="/eventos">Eventos</Link>
  </Button>
  <Button asChild>
    <Link href="/clientes">Clientes</Link>
  </Button>
  <Button asChild>
    <Link href="/sobre-nos">Sobre Nós</Link>
  </Button>
</nav>

        {children}
      </body>
    </html>
  );
}
